## Exercise 3 - Solution

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns

In [7]:
# Create an one-dimensional ndarray, dtype int, using python 
a = np.array([1,2,3,5,7.5,11,13,17])
# Print some array information
print(a)
print(a.shape)
print(a.dtype)

[ 1.   2.   3.   5.   7.5 11.  13.  17. ]
(8,)
float64


In [8]:
# Create atwo-dimensional ndarray, dtype float, using arange and reshape
b = np.arange(0, 100, 5, dtype=float).reshape(4,5)
# Print the array
print(b)
print(b.shape)
print(b.dtype)

[[ 0.  5. 10. 15. 20.]
 [25. 30. 35. 40. 45.]
 [50. 55. 60. 65. 70.]
 [75. 80. 85. 90. 95.]]
(4, 5)
float64


In [9]:
# Apply some arithmetic operations to the arrays (square)
a*a

array([  1.  ,   4.  ,   9.  ,  25.  ,  56.25, 121.  , 169.  , 289.  ])

In [10]:
# Apply some arithmetic operations to the arrays (square)
b*b

array([[   0.,   25.,  100.,  225.,  400.],
       [ 625.,  900., 1225., 1600., 2025.],
       [2500., 3025., 3600., 4225., 4900.],
       [5625., 6400., 7225., 8100., 9025.]])

In [11]:
# Calculate sum and mean of each column
a.sum()

59.5

In [12]:
# Calculate mean of each column
a.mean()

7.4375

In [43]:
# Calculate sum of each column
b.sum(axis=0)

array([150., 170., 190., 210., 230.])

In [44]:
# Calculate mean of each column
b.mean(axis=0)

array([37.5, 42.5, 47.5, 52.5, 57.5])